version: '3.6'

services:
  jenkins:
    image: "jenkins/jenkins:lts"
    container_name: "jenkins_test"
    volumes:
      - ./jenkins_home/:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock:rw
      - ./usr/bin/docker/:/usr/bin/docker
    # network_mode: host
    ports:
      - 8080:8080
      # - 50000:50000
    restart: always
  
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/www:/usr/share/nginx/html
      - ./cert:/etc/ssl/cert
    ports:
      - 80:80
      - 443:443 # Открываем порты для ssl соединения
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''  
    # Перезапустит nginx контейнер каждые 6 часов и подгрузит новые сертификаты, если есть
    restart: unless-stopped